
git:
  depth: 5

language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - xorg-dev
      - nasm

matrix:
  fast_finish: true
  exclude:
    - env: ""
  include:
    - env: COMPILER=g++-5 COMPILERC=gcc-5
    - env: COMPILER=g++-6 COMPILERC=gcc-6
    - os: osx
      compiler: clang
    - allow_failures:
      - os: osx
        compiler: clang

script:
  - export CXX=$COMPILER && export CC=$COMPILERC
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
  - cmake --build .
  - result/relwithdebinfo/cage-test-core
