
git:
  depth: 5

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - g++-7
      - g++-8
      - clang
      - xorg-dev

matrix:
  fast_finish: true
  exclude:
    - compiler: gcc
  include:
    - env: COMPILER=g++-6 COMPILERC=gcc-6 CONFIG=relwithdebinfo
    - env: COMPILER=g++-6 COMPILERC=gcc-6 CONFIG=debug
    - env: COMPILER=g++-7 COMPILERC=gcc-7 CONFIG=relwithdebinfo
    - env: COMPILER=g++-7 COMPILERC=gcc-7 CONFIG=debug
    - env: COMPILER=g++-8 COMPILERC=gcc-8 CONFIG=relwithdebinfo
    - env: COMPILER=g++-8 COMPILERC=gcc-8 CONFIG=debug
    - env: COMPILER=clang++ COMPILERC=clang CONFIG=relwithdebinfo
    - env: COMPILER=clang++ COMPILERC=clang CONFIG=debug
    - os: windows
      env: CONFIG=relwithdebinfo ARCH="x64"
    - os: windows
      env: CONFIG=debug ARCH="x64"
    - os: windows
      env: CONFIG=relwithdebinfo ARCH="Win32"
    - os: windows
      env: CONFIG=debug ARCH="Win32"
    - os: osx
      compiler: clang
      env: CONFIG=relwithdebinfo
  allow_failures:
    - os: osx
      compiler: clang
      env: CONFIG=relwithdebinfo

script:
  - export CXX=$COMPILER && export CC=$COMPILERC
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cmake -DCMAKE_BUILD_TYPE=$CONFIG .. ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ] ; then cmake -A $ARCH .. ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ] ; then cmake --build . ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ] ; then cmake --build . --config $CONFIG ; fi
  - result/$CONFIG/cage-test-core
  - result/$CONFIG/cage-asset-database

